### ISSUE TITLE
Маловато строк в файле!

### ISSUE THREAD

**Issue by Catethysis** [ValentiWorkLearning/catethysis_learning#1]
Я предлагаю добавить туда ещё пару строчек, ради интереса. @ValentiWorkLearning, обрати внимание!

**Comment by ValentiWorkLearning** [comment]
Да, добавим в ближайшее время.

**Comment by Catethysis** [comment]
Можешь потрогать маркдаун посильнее

**Comment by ValentiWorkLearning** [comment]
Все сделано.
